### ISSUE TITLE
How set the "skip" parameter in Hydra accept login request

### ISSUE THREAD

**Issue by mvsiva4u** [ory/hydra-login-consent-node#24]
Hi ,

I want to  set the "skip" parameter while calling below way. But it is throwing error . Can you please suggest is there any way we have to use.

hydra.acceptLoginRequest(challenge, {
                                            // Subject is an alias for user ID. A subject can be a random string, a UUID, an email address, ....
                                            subject: req.body.userid,
                                            skip:true,
                                            // This tells hydra to remember the browser and automatically authenticate the user in future requests. This will
                                            // set the "skip" parameter in the other route to true on subsequent requests!
                                            //remember: Boolean(req.body.remember),
                                            // When the session expires, in seconds. Set this to 0 so it will never expire.
                                            remember_for: 3600,

                                            // Sets which "level" (e.g. 2-factor authentication) of authentication the user has. The value is really arbitrary
                                            // and optional. In the context of OpenID Connect, a value of 0 indicates the lowest authorization level.
                                            // acr: '0',
                                        })

Thanks,

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not leave a comment or create a new issue, this issue will be auto-closed in 3 days.

/label needs-context

**Comment by lakshman1977** [comment]
Hi ,
 I am trying to use the example "as is",
![image](https://user-images.githubusercontent.com/53045640/62035548-a944c780-b222-11e9-8a7b-bd68e89c89f8.png)
i am getting error in the website
![image](https://user-images.githubusercontent.com/53045640/62035664-ddb88380-b222-11e9-88d6-4c990aa4db4c.png)
kindly advise

Thanks and Regards
Lakshman

**Comment by aeneasr** [comment]
Please follow the README: https://github.com/ory/hydra-login-consent-node#running-locally

Closing this issue because the original poster did not update the issue.
