### ISSUE TITLE
level=info msg="started handling request" method=GET remote="172.21.0.1:36528" request="/oauth2/auth/requests/login?login_challenge=e13c4939fd5a4730b006bb67a58cada5"

### ISSUE THREAD

**Issue by IsaacOc** [ory/hydra-login-consent-node#31]
results into :
request to http://x.x.x.x:4445/oauth2/auth/requests/login?login_challenge=24c4e87c9ce74e8791376e0c054f7c03 failed, reason: connect ECONNREFUSED x.x.x.x:4445

FetchError: request to http://1x.x.x:4445/oauth2/auth/requests/login?login_challenge=24c4e87c9ce74e8791376e0c054f7c03 failed, reason: connect ECONNREFUSED 127.0.0.1:4445
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

here Idea why on window 10 docker hdyra

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not leave a comment or create a new issue, this issue will be auto-closed in 3 days.

/label needs-context
